language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer install --prefer-source --no-dev --no-interaction
    - composer dump-autoload --no-dev

script: vendor/bin/phpunit

notifications:
    email: false
